name: traintest123
model_type: Riemer123


name: FFHQ_train
type: FFHQsubDataset
dataroot_gt: ./data/train/GT
meta_info: ./data/train/meta_info_FFHQ5000sub_GT.txt
io_backend: {'type': 'disk'}
  # type: disk

blur_kernel_size: 21
kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
sinc_prob: 0.1
blur_sigma: [0.2, 3]
betag_range: [0.5, 4]
betap_range: [1, 2]

blur_kernel_size2: 21
kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
sinc_prob2: 0.1
blur_sigma2: [0.2, 1.5]
betag_range2: [0.5, 4]
betap_range2: [1, 2]

final_sinc_prob: 0.8

gt_size: 512
use_hflip: True
use_rot: False

# data loader
use_shuffle: true
num_worker_per_gpu: 6
batch_size_per_gpu: 8
dataset_enlarge_ratio: 1000
prefetch_mode: ~
